### PR TITLE
Run `go test` and have passing tests

### PR DESCRIPTION
**Pull request by onlydole**
*Issue #, if available:*

* `go test` does not result in passing tests due to the package references.
* `go fmt` was not run on the `main.go` and `main_test.go` files

*Description of changes:*

I have run `go fmt` on both main* files and updated the main_test.go to reliably run the tests included. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PaulMaddox** [comment]
Hi @onlydole,

Can you provide more detail on where/how you see tests failing?
There should not be a problem with the package references.

For me:

```bash
$ go get github.com/aws-samples/lambda-go-samples
$ cd $GOPATH/src/github.com/aws-samples/lambda-go-samples
$ go test .
ok      github.com/aws-samples/lambda-go-samples        0.044s
```

I got into the habit of testing from a different package when I first started with Go, as it helps ensure you're only testing your publicly exposed API. On a small example like this, it doesn't make such a big deal, however on larger projects it helps.

**Comment by onlydole** [comment]
Hey @PaulMaddox! 

Thank you for getting back to me so quickly. 

I do like testing from a different package with tests for publicly exposed APIs. My use case was more around modifying and testing code locally. 

I'm using the latest on GitHub as my "source of truth" and my path is `$GOPATH/src/lambda-go-samples` is the cause for some errors I was seeing, undoubtedly.

```
cd $GOPATH/src
git clone git@github.com:aws-samples/lambda-go-samples.git 
go get
go test 

main_test.go:6:2: cannot find package "github.com/aws-samples/lambda-go-samples"...
FAIL	lambda-go-samples [setup failed]
```

If I wanted to test locally, I could change the main alias to be: `main "lambda-go-samples"` in my use case and the tests do pass without issue. 

My concern around using `go get github.com/aws-samples/lambda-go-samples` is that the developer will always need to keep that up to date if that code updates, outside of git (here, you're right...it most likely wouldn't change / matter so much though).

**Comment by PaulMaddox** [comment]
This is due to you checking out the sample manually to $GOPATH/src/lambda-go-samples. Go packages are normally checked out to their canonical path (including the full import path) in your $GOPATH.

If you use `go get` instead of manually cloning the repository you'll find that places it in the right location automatically. I'm not sure I follow your comment regarding the developer (you?) needing to keep the import up to date outside of git.

Standard best practices with Go would be to use `go get` to fetch a dependency, and `go get -u <package>` to update a dependency. In addition, you could also vendor in the `aws-lambda-go` package if you wanted, using something like `dep`.

Of course, you're more than welcome to checkout the project to anywhere you want in your $GOPATH, however you will need to adjust the import to match.

I'm going to close this PR, as I believe this is more personal preference than standard Go practise.

**Comment by onlydole** [comment]
@PaulMaddox - To confirm, best practice would be to separate tests from your underlying code (not running tests against the main function in the repository?) That's the context that feels odd as it's not using Git as the source of truth...do you know any "best practices" guides for that on golang.org / elsewhere that I could reference and wrap my head around?

**Pull request closed without merging**
